version: 2.1
executors:
  docker-executor:
    docker:
      - image: docker:latest

jobs:
  build:
    executor: docker-executor
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Log in to GHCR
          command: echo $CR_PAT | docker login ghcr.io -u $GITHUB_USERNAME --password-stdin
      - run:
          name: Build Docker Image
          command: docker build -t ghcr.io/${GITHUB_USERNAME}/my-image:latest .
      - run:
          name: Push Docker Image
          command: docker push ghcr.io/${GITHUB_USERNAME}/my-image:latest

  deploy:
    executor: docker-executor
    steps:
      - add_ssh_keys:
          fingerprints:
            - '<your-fingerprint>'
      - run:
          name: Copy docker-stack.yaml to VPS
          command: scp -o StrictHostKeyChecking=no docker-stack.yaml $VPS_USER@$VPS_HOST:/path/to/deploy
      - run:
          name: Deploy Docker Stack
          command: |
            ssh -o StrictHostKeyChecking=no $VPS_USER@$VPS_HOST "docker stack deploy -c /path/to/deploy/docker-stack.yaml my-stack"

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only:
                - main
