name: pipeline
on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - 'main'
permissions:
  packages: write
jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Login to container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            ghcr.io/pmi-project/warehouse-client:latest
            ghcr.io/pmi-project/warehouse-client:${{ github.sha }}
          build-args: |
            NEXT_PUBLIC_DEVICE_HUB=${{ secrets.NEXT_PUBLIC_DEVICE_HUB }} 
            AUTH_URL_DEV=${{ secrets.AUTH_URL_DEV }}
  deploy:
    runs-on: ubuntu-latest
    needs:
      - build-and-push-image
    steps:
      - name: checkout repo
        uses: actions/checkout@v4

      - name: docker stack deploy
        uses: cssnr/stack-deploy-action@v1
        with:
          name: artix-wms
          file: docker-stack.yaml
          host: artix-labs.com
          user: artixlabs
          ssh_key: ${{ secrets.DEPLOY_SSH_PRIVATE_KEY }}
